all:
  hosts:
    node1:
      ansible_host: 192.168.50.10
      ip: 192.168.50.10
      access_ip: 192.168.50.10
    node2:
      ansible_host: 192.168.50.21
      ip: 192.168.50.21
      access_ip: 192.168.50.21
    node3:
      ansible_host: 192.168.50.22
      ip: 192.168.50.22
      access_ip: 192.168.50.22
    node4:
      ansible_host: 192.168.50.23
      ip: 192.168.50.23
      access_ip: 192.168.50.23
    node5:
      ansible_host: 192.168.50.24
      ip: 192.168.50.24
      access_ip: 192.168.50.24
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
